config/routes.rb
Rails.application.routes.draw do
  root to: 'weather_temperatures#index'
  get '/prediction', to: 'weather_temperatures#weather_prediction', as: 'weather_predictions'

  resources :weather_temperatures
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/weather_temperature.rb
class WeatherTemperature < ApplicationRecord
  def self.get_temps(limit)
    limit(limit).pluck(:temp_c)
  end

  def self.get_avg_by_month_temps
    WeatherTemperature.group(Arel.sql("DATE_TRUNC('month', created_at)"))
                      .order(Arel.sql("DATE_TRUNC('month', created_at)"))
                      .average(:temp_c)
                      .transform_keys { |key| key.strftime("%B") }
                      .transform_values { |value| value.to_i }
  end

  def self.get_week_temps(location)
    WeatherPicker.new.forecast_weather_week(location)[:temperatures]
  end

  def self.get_location(location)
    WeatherPicker.new.forecast_weather_week(location)[:location]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_temperatures_controller.rb
class WeatherTemperaturesController < ApplicationController
  def index
    gon.avg_temps_by_month = WeatherTemperature.get_avg_by_month_temps
  end

  def weather_prediction
    gon.temps = WeatherTemperature.get_week_temps(params[:location])
    gon.location = WeatherTemperature.get_location(params[:location])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_temperatures_helper.rb
module WeatherTemperaturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherHotwires</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= include_gon %>
  </head>

  <body>
    <nav class="bg-gray-800">
      <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div class="flex h-16 items-center justify-between">
          <div class="flex items-center">
            <div class="flex-shrink-0">
              <img class="h-8 w-8" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
            </div>
            <div class="hidden md:block">
              <div class="ml-10 flex items-baseline space-x-4">
                <%= link_to 'Dashboard', root_path, class: 'text-white rounded-md px-3 py-2 text-sm font-medium' %>
                <%= link_to 'Prediction', weather_predictions_path, class: 'text-white rounded-md px-3 py-2 text-sm font-medium' %>
                <%# <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Team</a> %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </nav>

  <%= notice %>
  <%= alert %>
  <%= yield %>
  </body>
</html>

app/views/weather_temperatures/index.html.erb
<div class="min-h-full">
  <header class="bg-white shadow">
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">Dashboard</h1>
    </div>
  </header>
  <main>
    <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
      <div data-controller="metric">
        <canvas id="metric" data-metric-target="myChart" width="800" height="450"></canvas>
      </div>
    </div>
  </main>
</div>

app/views/weather_temperatures/weather_prediction.html.erb
<div class="min-h-full">
  <main>
    <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
      <div class="p-8 mx-auto rounded-lg dark:bg-gray-900 dark:text-gray-100">
        <div data-controller="prediction">
          <div id="prediction" data-prediction-target="weatherHeader"></div>
          <canvas id="prediction" data-prediction-target="myChart" class="rounded-lg" width="1200" height="300"></canvas>
          <div id="prediction" data-prediction-target="weatherList"></div>
        </div>
      </div>
    </div>
  </main>
</div>